disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "simonedimaria's blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "static/logo.png"
secondaryLogo = "static/logo.png"
description = "simonedimaria blog description"
author = { name = "simonedimaria", image = "gatto-stregone-ciccione.jpeg", headline = "`Web2/Web3 CTF player for TheRomanXpl0it`", bio = "palle bio" }

[author]
links = []
