# config/_default/menus.toml

[[main]]
    none = "none"

[[main]]
    name = "Blog"
    pageRef = "posts"
    weight = 1

[[main]]
    name = "Tags"
    pageRef = "tags"
    weight = 1

[[main]]
    identifier = "x-twitter"
    pre = "x-twitter"
    url = "https://x.com/dimariasimone"
    weight = 2

[[main]]
    identifier = "github"
    pre = "github"
    url = "https://github.com/simonedimaria"
    weight = 3

[[footer]]
    name = "Tags"
    pageRef = "tags"
    weight = 10
