[[main]]
none = "none"

[[main]]
name = "Title"
pre = "heart"
pageRef = "newSite"
identifier = "gv5r3ka2nX"
weight = 9999

[[footer]]
none = "none"

[[footer]]
name = "footer"
pageRef = "newSite"
identifier = "QGICeiKOsQ"
weight = 9999
